[build]
target = "riscv32i-unknown-none-elf"

[target.'cfg(all(target_arch = "riscv32", target_os = "none"))']
rustflags = [
  "-C", "link-arg=-Tneorv32.ld",

  # If you encounter any problems with LLD, switch to GNU linker by:
  "-C", "linker=riscv32-unknown-elf-ld",
]
